version: "3"
services:
  geo:
    build: .
    ports:
      - "80:8083"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PASS=
      - LISTEN_PORT=8083
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./persist/mongo:/data/db
